services:
  database:
    container_name: "muffin_database"
    image: mariadb:11.4.2
    volumes:
      - "./database/:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
      - "./scripts/:/docker-entrypoint-initdb.d/"
    ports:
      - "1502:3306"
    env_file:
      - "./docker.env"
    networks:
      - muffin_ai
  discord_bot:
    container_name: "maa"
    build: "."
    networks:
      - muffin_ai
    depends_on:
      - database
    env_file:
      - "./.env"

networks:
  muffin_ai:
      driver: bridge